# ATF4 Project
## Check if the starting point of the next simulation is sufficiently similar to the last frame of the trajectory

### Chuan Ping
#### Mar 2, 2022

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import mdtraj as md
import MDAnalysis as mda

import nglview as nv
import ipywidgets

%matplotlib inline
%config InlineBackend.figure_format='retina'

plt.style.use('bmh')

In [2]:
# load the two trajectory files. 

traj_nw = md.load_hdf5('/Users/cping/Desktop/ATF4/replica3/traj_nw_replica_3.h5') 
traj_restart_nw = md.load_pdb('/Users/cping/Desktop/ATF4/replica3/restart_3_nw.pdb')

#center the two trajectories at (0,0,0) so when it is viewed, it will not jump around.
traj_nw.center_coordinates(traj_nw)
traj_restart_nw.center_coordinates(traj_restart_nw)

#displays some basic properties of the trajectories.
print(traj_nw)
print(traj_restart_nw) #The number of frames here should be 1

<mdtraj.Trajectory with 11464 frames, 5380 atoms, 352 residues, and unitcells>
<mdtraj.Trajectory with 1 frames, 5380 atoms, 352 residues, and unitcells>


In [4]:
# Shows the trajectory of interest without water
show_nw = nv.show_mdtraj(traj_nw)
show_nw

NGLWidget(max_frame=11463)

In [5]:
# Shows the restart.pdb file
show_restart_nw = nv.show_mdtraj(traj_restart_nw)
show_restart_nw

NGLWidget()

In [6]:
# Shows the last frame of the trajectory of interest
last_frame = traj_nw[-1]
show_last_frame = nv.show_mdtraj(last_frame)
show_last_frame

NGLWidget()

In [7]:
# Calculate the radius of gyration of the last frame
rg_nw = md.compute_rg(last_frame)
rg_nw

array([2.91602798])

In [8]:
rg_restart_nw = md.compute_rg(traj_restart_nw)
rg_restart_nw

array([2.91602749])

In [9]:
# If the difference is sufficiently small, then we are sure that the restart.pdb file is indeed the last frame
# of the trajectory. 
difference = rg_nw - rg_restart_nw
difference

array([4.88277788e-07])